### ISSUE TITLE
[Far x86 on Windows 7 SP1 **x64**] Error: WOW64 is not supported. Please use the x64 version.

### ISSUE THREAD

**Issue by dr-dba** [alabuzhev/unicon#2]
issue in Far x86 (all versions) on Windows 7 x64
![image](https://user-images.githubusercontent.com/57611392/154617707-540392ed-4765-4b7f-acb7-99892eca7dda.png)

**Comment by alabuzhev** [comment]
[WOW64 is not supported. Please use the x64 version](https://github.com/alabuzhev/unicon/issues/1#issuecomment-901067123).
